# Generated by Django 3.1.7 on 2021-03-08 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catologue', '0003_auto_20210308_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='catologue.manufacturer'),
        ),
    ]
