# Generated by Django 3.1.7 on 2021-03-10 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catologue', '0004_auto_20210308_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SubcategoryFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='subcategory_parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='catologue.subcategory'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='manufacturer_name',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='catergory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='catologue.category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_name',
            field=models.CharField(max_length=32),
        ),
        migrations.DeleteModel(
            name='ProductFields',
        ),
        migrations.AddField(
            model_name='subcategoryfeature',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catologue.subcategory'),
        ),
        migrations.AddField(
            model_name='productvalues',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catologue.subcategoryfeature'),
        ),
        migrations.AddField(
            model_name='productvalues',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catologue.product'),
        ),
    ]
