# Generated by Django 3.1.7 on 2021-03-11 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catologue', '0005_auto_20210310_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catologue.subcategoryfeature')),
            ],
        ),
        migrations.CreateModel(
            name='SubcategoryValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=32)),
                ('subcategoryfeature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catologue.subcategoryfeature')),
            ],
        ),
        migrations.RemoveField(
            model_name='productvalues',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='productvalues',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='catergory',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='catologue.category', to_field='category_name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.SlugField(unique=True),
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
        migrations.DeleteModel(
            name='ProductValues',
        ),
        migrations.AddField(
            model_name='productitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catologue.product'),
        ),
        migrations.AddField(
            model_name='productitems',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catologue.subcategoryvalues'),
        ),
    ]
